DEVICE_DEV_PATH = "/dev/"
DEVICE_CALLINGUNIT_NAME = "cu.usbmodem"

NEW_LINE_CHARACTER = "\n"
DEFAULT_BAUD = 115200
DEFAULT_SLEEP = 0.5
DEFAULT_ENCODING = "utf-8"
GRBL_WAKEUP_COMMAND = "\r\n\r\n"
GRBL_HOME_COMMAND = "$H"
GRBL_ZERO_COMMAND = "G92 X0 Y0"
GRBL_MOVE_COMMAND_1 = "G1 X0 Y0 F2000"
GRBL_MOVE_COMMAND_2 = "G1 X10 Y10 F2000"
GRBL_TAB_COMMAND_1 = "m3 s90"
GRBL_TAB_COMMAND_2 = "m5"
